2.0.0 experimental.53
daostack/arc.js pull request #528
Opened 2020-09-04 08:18 UTC by jellegerbrandy

2020-09-04 11:14 UTC, dkent600 requested changes
If this is a problem with importing BigNumber, should we not also be addressing its use in arc.ts and token.ts?

2020-09-04 13:36 UTC, jellegerbrandy commented
I updated the description of this PR

2020-09-06 07:12 UTC, orenyodfat commented
Join test : `invalid BigNumber value (arg="value", value="3e8", version=4.0.47)` 
@roienatan @jellegerbrandy ?

2020-09-06 07:41 UTC, roienatan commented
> Join test : `invalid BigNumber value (arg="value", value="3e8", version=4.0.47)`
> @roienatan @jellegerbrandy ?

Strange since we're not using BigNumber in the join test. Probably it uses arc.ts which uses BigNumber.
Anyway, according to the issue you @jellegerbrandy describe here, why not eliminate all the ueses of BigNumber and use BN instead? There are not many places that use BigNumber and it's better to stick to one library.

2020-09-06 11:52 UTC, closed without merging